# Generated by Django 3.0 on 2020-07-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('location', models.CharField(choices=[{'kitchen', 'KT'}, {'CL', 'Cell'}, {'CF', 'Cafeteria'}, {'GR', 'Garden'}, {'Shower', 'SH'}], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmate_name', models.CharField(max_length=100)),
                ('inmate_surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('cell_num', models.CharField(max_length=10)),
                ('intake_time', models.DateTimeField()),
                ('dude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmates_register.History')),
            ],
        ),
    ]
