# Generated by Django 3.0 on 2020-07-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(choices=[{'KT', 'kitchen'}, {'CL', 'Cell'}], max_length=2),
        ),
    ]
