# Generated by Django 3.0 on 2020-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0002_auto_20200709_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(choices=[{'KT', 'kitchen'}, {'CL', 'Cell'}, {'CF', 'Cafeteria'}, {'GR', 'Garden'}, {'SH', 'Shower'}], max_length=8),
        ),
    ]
