# Generated by Django 3.0 on 2020-07-09 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0005_auto_20200709_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmate',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='inmate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inmates_register.InMate'),
            preserve_default=False,
        ),
    ]
