# Generated by Django 3.0 on 2020-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0006_auto_20200709_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(choices=[{'KT', 'kitchen'}, {'Cell', 'CL'}, {'Garden', 'GR'}, {'Cafeteria', 'CF'}, {'Shower', 'SH'}], max_length=15),
        ),
    ]
