# Generated by Django 3.0 on 2020-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0007_auto_20200709_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(choices=[{'CL', 'Cell'}, {'Garden', 'GR'}, {'CF', 'Cafeteria'}, {'SH', 'Shower'}, {'KT', 'kitchen'}], max_length=15),
        ),
    ]
