# Generated by Django 3.0 on 2020-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0008_auto_20200709_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(choices=[{'Cell', '1'}, {'2', 'Garden'}, {'Cafeteria', '3'}, {'Shower', '4'}, {'5', 'kitchen'}], max_length=15),
        ),
    ]
