# Generated by Django 3.0 on 2020-07-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0009_auto_20200709_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='time_end',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='history',
            name='time_start',
        ),
    ]
