# Generated by Django 3.0 on 2020-07-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0012_auto_20200710_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(choices=[('CL', 'Cell'), ('GR', 'Garden'), ('CF', 'Cafeteria'), ('SH', 'Shower'), ('KT', 'Kitchen')], max_length=15),
        ),
    ]
