# Generated by Django 3.0 on 2020-07-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0016_auto_20200713_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='inmate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inmates_register.InMate'),
        ),
    ]
