# Generated by Django 3.0 on 2020-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmates_register', '0017_auto_20200713_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(choices=[('Cel', 'Cell'), ('Gard', 'Garden'), ('Caf', 'Cafeteria'), ('Show', 'Shower'), ('Kit', 'Kitchen')], max_length=15),
        ),
    ]
